### ISSUE TITLE
[Bug] the page action icon is missing after update to 1.0.1

### ISSUE THREAD

**Issue by MikkCZ** [shgysk8zer0/awesome-rss#45] opened 2017-09-26 14:19 UTC
After the last update, I see a blank space instead of the icon. Looking into the preferences the theme select is empty and highlighted in red as invalid. Choosing the icon from the lists works and fixes the issue.

**Comment by shgysk8zer0** [comment] 2017-09-26 18:30
Although stated differently, this is a duplicate of #43. I was storing the path to icons as the `value`s, and when I renamed them, the paths to existing settings was no longer valid. I'm updating how I store icon selection by storing the key to an object that will store it's path.

Not sure how to test the update process, since I only know how to test using `web-ext run` or by loading as temporary icon, both of which would be a new install rather than an update.

**Closed by shgysk8zer0** 2017-09-26 18:30 UTC
Labels: enhancement
