### ISSUE TITLE
Problem with URL Tooltip WE

### ISSUE THREAD

**Issue by happysurf** [shgysk8zer0/awesome-rss#67] opened 2018-03-01 16:31 UTC
### Steps to reproduce
1.  Load URL Tooltip WE extension to https://addons.mozilla.org/en-US/firefox/addon/url-tooltip-we/?src=api
2.  Move the mouse cursor over a link like in this page (Code, Issue, Pull request....). 

### Expected behavior
The RSS icon must be remain fixed.

### Actual behavior
When the mouse cursor pass over a link the RSS icon flickers. 
Without URL Tooltip WE extension disabled all is OK.

**Comment by shgysk8zer0** [comment] 2018-03-01 16:46
Duplicate of #61

**Closed** 2018-03-01 16:47 UTC
Labels: duplicate

**Comment by happysurf** [comment] 2018-03-01 16:51
Sorry, but the problem can be solved in your extension or by the URL Tooltip WE developer, what you think?
Thanks.

**Comment by shgysk8zer0** [comment] 2018-03-01 18:51
I can't really say. I honestly don't get the point of the add-on and consider it to remove rather than add to UX, since the URL is already displayed in the bottom right when a link is hovered and this only eliminates any use of `title` to tell users where a link leads to.

In scanning through UTW source, I think that the problem is mostly on their end. It's difficult to follow because I really have no clue what they are attempting to do in any of it or why, but the following line is a likely culprit:

```js
history.replaceState(history.state, document.title);
```

The flash you see is caused by me re-scanning the page whenever the tab/URL is updated. I have to do this for AJAX navigation, which would use `fetch` and `history` to provide navigation. Whenever the page is updated, I have to hide the icon, scan the updated page for feeds, and re-display the icon if any are found. The only real alternative to this is to show the icon by default, which results in it being displayed on some pages that don't have feeds and/or the add-on won't work on (many Mozilla pages disable add-ons, as you can see in closed issues).

I'm pretty sure there's a way I could improve scanning updated pages to avoid this flash, but I really don't see any reason UTW should be triggering a page update in order to change a link's `title` to it's `href`.

**Comment by happysurf** [comment] 2018-03-02 08:20
Thanks, for now I have disabled the option >**Hide status panel** in UTW.
I want suggest your opinion to UTW developer, if you want of course.
Thanks.

**Comment by shgysk8zer0** [comment] 2018-03-02 09:07
Sure. Feel free to do so.
