### ISSUE TITLE
Button not working

### ISSUE THREAD

**Issue by olloff** [shgysk8zer0/awesome-rss#14] opened 2017-09-10 08:10 UTC
Affected browser v.: at least FF 55.0.3 (current stable) and FF 57.0.a1 (current nightly).
Affected addon v.: 0.1.0

### Steps to reproduce
1.  Go to any website announcing XML RSS, for example, https://naked-science.ru/article/sci/virus-zika-mozhet-stat-sredstvom-borby
2.  Press the feed button

### Expected behavior
Idk, maybe feed list should be displayed, depends of addon's way to manage it

### Actual behavior
Nothing happens

### Screenshots and/or logs (see how to open the developer console in your browser)
There is at least one line associated with this bug:
```
TABS[tab.id] is undefined  background.js:26
	clickHandler moz-extension://5e466cc1-2fac-4688-8a81-a68b75e89992/background.js:26:3
	runSafeSyncWithoutClone resource://gre/modules/ExtensionUtils.jsm:52:14
	runSafeWithoutClone resource://gre/modules/ExtensionCommon.jsm:176:38
	receiveMessage resource://gre/modules/ExtensionChild.jsm:763:61
	_callHandlers/< resource://gre/modules/MessageChannel.jsm:585:17
	_callHandlers resource://gre/modules/MessageChannel.jsm:584:14
	_handleMessage/deferred.promise< resource://gre/modules/MessageChannel.jsm:649:7
	_handleMessage resource://gre/modules/MessageChannel.jsm:646:24
	_handleMessage self-hosted:945:17
	receiveMessage resource://gre/modules/MessageChannel.jsm:163:5
```

**Comment by shgysk8zer0** [comment] 2017-09-10 09:04
Hey. Thanks for letting know, but this is a duplicate of issue #12, which was fixed yesterday. Mozilla just takes a while to review changes.

The update should be available within a few hours, or it could be a couple of days.

**Closed** 2017-09-10 09:05 UTC

**Comment by olloff** [comment] 2017-09-10 09:10
Sorry about that, I should use search more often.

**Comment by shgysk8zer0** [comment] 2017-09-10 14:58
No problem. Closed issues are easily missed.

Update was approved, so button will work now, though still only for the first feed found.
